runtime: python311

entrypoint: gunicorn -b :$PORT main:covid_ct

handlers:
- url: /static
  static_dir: static
- url: /uploads
  static_dir: uploads
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  PYTHON_VERSION: '3.11'
  FLASK_ENV: production
